name: deploy-to-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: touch .nojekyll
    - run: npm install
    - run: npm run export
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir:  coding-pages
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
